name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test_x64:
    runs-on: windows-latest
    name: Test x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          repository-cache: true
          bazelrc: |
            common --curses=no

      - name: Run tests
        shell: cmd
        working-directory: tests
        run: test_host_x64.bat

  test_arm64:
    runs-on: windows-11-arm
    name: Test ARM
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          repository-cache: true
          bazelrc: |
            common --curses=no

      - name: Run tests
        shell: cmd
        working-directory: tests
        run: test_host_arm64.bat
