name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test_x64:
    runs-on: windows-latest
    name: Test x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          repository-cache: true
          bazelrc: |
            common --curses=no

      - name: Run test_default
        working-directory: tests
        run: python integration_test.py test_default

      - name: Run all_hosts_all_targets
        working-directory: tests
        run: python integration_test.py all_hosts_all_targets

      - name: Run one_host_one_target
        working-directory: tests
        run: python integration_test.py one_host_one_target

  test_arm64:
    runs-on: windows-11-arm
    name: Test arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          repository-cache: true
          bazelrc: |
            common --curses=no

      - name: Run test_default
        working-directory: tests
        run: python integration_test.py test_default

      - name: Run all_hosts_all_targets
        working-directory: tests
        run: python integration_test.py all_hosts_all_targets

      - name: Run one_host_one_target
        working-directory: tests
        run: python integration_test.py one_host_one_target
